name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: mom-gen
          region: asia-southeast2
          source: .
          env_vars: |
            PROVIDER=openai
            MODEL_ID=gpt-4o-mini
            MAX_TOKENS=700
            TEMPERATURE=0.2
            LOG_LEVEL=info
            CORS_ORIGIN=*
            ALLOWLIST_EMAILS=wsnwrdna2@gmail.com
            FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
            FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}
            FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          flags: |
            --memory=256Mi
            --cpu=0.25
            --min-instances=0
            --max-instances=1
            --no-allow-unauthenticated